


version: '3.8'

services:
  web:
    build:
      context: .  # Specify the build context
      dockerfile: Dockerfile  # Specify the Dockerfile if not named 'Dockerfile'
      args:
        DATABASE_URL: mysql+pymysql://root:140610@db/sgb
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://root:140610@db/sgb
    depends_on:
      db:
        condition: service_healthy  # Wait for the db to be healthy
    networks:
      - flask-mysql-network
      - flask-internet
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 140610
      MYSQL_DATABASE: sgb
    ports:
      - "3306:3306"
    networks:
      - flask-mysql-network
      - flask-internet
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  flask-mysql-network:
    internal: true
  flask-internet:
    internal: false
    driver: bridge

volumes:
  db_data:
