"""Initial migration.

Revision ID: 6e4f0808b489
Revises: 
Create Date: 2024-10-30 10:15:20.454783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4f0808b489'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('ano_publicacao', sa.Integer(), nullable=True),
    sa.Column('genero_id', sa.Integer(), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.Column('url_da_capa', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['autor.id'], ),
    sa.ForeignKeyConstraint(['genero_id'], ['genero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emprestimo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('membro_id', sa.Integer(), nullable=False),
    sa.Column('data_emprestimo', sa.DateTime(), nullable=False),
    sa.Column('data_devolucao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['livro.id'], ),
    sa.ForeignKeyConstraint(['membro_id'], ['membro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprestimo')
    op.drop_table('livro')
    op.drop_table('membro')
    op.drop_table('genero')
    op.drop_table('autor')
    # ### end Alembic commands ###
